;MULTIPLICATION OF TWO NUMBERS WITHOUT USING 'MUL' OPERATION, BY USING REPEAT COMMAND
DATA SEGMENT
    M DW 5
    N DW 3
    PRODUCT DW 0
ENDS

CODE SEGMENT
    START:
    MOV AX, @DATA
    MOV DS, AX
    MOV AX, [M]   ;AX = 5    
    MOV BX, [N]   ;BX = 3
    
    REPEAT:
    ADD [PRODUCT], AX   ;Product = 5
    DEC BX
    CMP BX, 0
    JNE REPEAT
    MOV DI, [PRODUCT]
ENDS
END START
